spring.application.name=healthcare

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/healthcare_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
spring.datasource.username=healthcare_user
spring.datasource.password=healthcare_user
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect